language: python
sudo: required

python:
  - "2.7"
  - "3.4"

virtualenv:
      system_site_package: true

install:
  - pip install -r requirements.txt
  - python setup.py install

script:
 - python  unittestcases/xinge_unittest.py
 - python  unittestcases/xinge3_unittest.py
